encuesta = {
    "Pregunta 1":{"text":"¿Cuál es tu objetivo de inversión?",
                  "opc":["Vivienda","Ahorro","Proyectos Personales","Retiro","Educación"]},
    "Pregunta 2": {"text":"¿Cuál es tu nivel educativo?",
                   "opc":["Básica primaria","Bachillerato","Universitario","Posgrado"]},
    "Pregunta 3": {"text":"¿Aproximadamente ¿Cuanto desea invertir en nuestro portafolio??",
                   "opc":["Ingrese valor"]},
    "Pregunta 4":{"text":"¿Qué edad tiene?",
                  "opc":["Más de 50","Entre 40 - 50","Entre 30 - 40","Entre 18 - 30"],
                  "valor":[1,2,3,4]},
    "Pregunta 5":{"text":"¿En cuánto tiempo esperaria usted hacer uso de los recursos invertidos?",
                  "opc":["Menor a 1 año","Entre 2 a 5 años","Entre 5 a 10 años","Más de 10 años"],
                  "valor":[1,2,3,4]},
    "Pregunta 6":{"text":"De acuerdo al horizonte de inversión, y a su  capacidad de asumir riesgo, espera una rentabilidad anual de:",
                  "opc":["5%","7% - 9%","10% - 13%","14% - 20%"],
                  "valor":[1,2,3,4]},
    "Pregunta 7":{"text":"¿Qué proporción aproximada del total de su patrimonio representa esta inversión?",
                  "opc":["Más del 50%","Del 20% - 50%","Menos del 20%","Menos del 5%"],
                  "valor":[1,2,3,4]},
    "Pregunta 8":{"text":"¿Cúal es mi conocimiento dentro del mercado financiero ?",
                  "opc":["Ninguno","Bajo (cuentas corrientes, CDT's)","Medio(Inversión en renta fija, Renta variable, Divisas,Fondos de inversión colectiva, Fondos de pensiones voluntarias)","Alto (Adicional a lo anterior, he tenido conocimiento en Derivados, notas estructuradas, coberturas de cartera)"],
                  "valor":[1,2,3,4]},
    "Pregunta 9":{"text":"¿Cuál es el escenario que mejor se adecúa a las expectativas personales para el resultado de esta inversión?",
                  "opc":["Estabilidad: Prefiero seleccionar inversiones con pocas fluctuaciones y bajo riesgo en el corto plazo aceptando rentabilidades conservadoras",
                         "Algunas volatilidades: Puedo aceptar algunas volatilidades diarias en el valor de mi inversión (subidas y caídas en su precio), si esto significa que obtendré ganancias moderadas.",
                         "Grandes fluctuaciones: Invierto en activos que pueden tener grandes fluctuaciones en el corto plazo (subidas y caídas en su precio) como acciones, entiendo que estos pueden tener grandes valorizaciones y una alta rentabilidad en el largo plazo"],
                  "valor":[1,2,3,4]},
    "Pregunta 10":{"text":"De acuerdo a lo anterior, usted esta dispuesto a aceptar una pérdida máxima de:",
                  "opc":["10% de su inversión","20% de su inversión","Hasta el 50% de su inversión"],
                  "valor":[1,2,3]},
    "Pregunta 11":{"text":"¿Cuantas personas dependen financieramente de usted? ",
                  "opc":["Más de 3","Entre 2 a 3","Entre 0- 1"],
                  "valor":[1,2,3]},
    "Pregunta 12":{"text":"Suponiendo desvalorización de mi inversión en el corto plazo, mi decisión sería:",
                  "opc":["Liquidar la totalidad del portafolio","Liquidar parte del portafolio reinvirtiendo el porcentaje retirado en activos más seguros",
                         "Esperar que el portafolio se recupere y/o comprar activos más riesgosos, que me permitan recuperar las pérdidas en el largo plazo o aprovechar activos que hayan bajado de precios y están baratos"],
                  "valor":[1,2,3]},
    "Pregunta 13":{"text":"Si por ejemplo invierte usted 10 millones de pesos, en un plazo a un año estaría dispuesto aceptar una pérdida máxima de:",
                  "opc":["500 mil pesos","1 Millon de pesos","2 Millones de pesos","3 Millones de pesos"],
                  "valor":[1,2,3]},
    "Pregunta 14":{"text":"Para usted, una volatilidad alta es de: (Respuesta en %)",
                  "opc":["Ingrese aqui su respuesta"]},
}